import { Oswald } from 'next/font/google';
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from './components/Footer';

const oswald = Oswald({
  subsets: ['latin'],
  variable: '--font-oswald',
});

export const metadata = {
  title: "QUICKCART",
  description: "Generated by create next app",
  icons: {
    icon: "/Images/cart.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${oswald.className} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
